name: xshop_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^0.5.12
  rflutter_alert: ^1.1.0

  flutter_bloc: ^3.2.0
  sqflite: ^1.2.0
  path: ^1.6.4
  sticky_headers: ^0.1.7
  qr_flutter: ^3.1.0
  provider: ^4.1.3
  audioplayers: ^0.17.4
  





  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  progress_dialog: ^1.2.0
  modal_progress_hud: ^0.1.2
  transparent_image: ^1.0.0
  material_design_icons_flutter: ^4.0.5955
  json_annotation: ^3.1.1
  backdrop: ^0.6.2
  qr_code_scanner: ^0.3.5
  web_socket_channel: ^1.2.0
  webview_flutter: ^2.0.9
  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  esc_pos_bluetooth: ^0.2.8
  esc_pos_printer: ^3.1.6
  esc_pos_utils: ^0.3.6
  path_provider: ^1.6.28
  flutter_launcher_icons: ^0.7.0
  hive: ^1.4.4+1
  hive_flutter: 
  flutter_webview_plugin: ^0.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.4

  json_serializable: ^3.5.1
  build_runner: ^1.10.9
  hive_generator: 
  flutter_native_splash: ^0.3.2
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

    - images/try.jpg
    - images/an.jpg
    - images/shop.jpg
    - images/meeting.jpg
    - images/signup.jpeg
    - images/invoice.png
    - images/Cashier-Area.jpg
    - assets/sou.mp3

    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash: 
    color: "#f5f5f5"
    image: "images/icon/icon.png"
    android: true
    ios: true

